name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: read
  id-token: write # for NuGet trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - run: echo "VERSION=${VERSION#v}" >> "$GITHUB_ENV"

      - run: dotnet build -c Release -p:Version=$VERSION
      - run: dotnet pack -c Release --no-build -p:Version=$VERSION -o nupkg

      - uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - run: dotnet nuget push nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
